### ISSUE TITLE
Implement search indexes

### ISSUE THREAD

**Issue by codemicro** [codemicro/surchable#11]
**Description**: Search indexes will store the tokenised input from the digest page endpoint. This is going to be done based on [this article](https://bart.degoe.de/building-a-full-text-search-engine-150-lines-of-code/) and will include stemming.

**Branch:** [`11-searchIndexes`](https://www.github.com/codemicro/surchable/tree/11-searchIndexes), #13

**To-do:**
- [x] Alter SQL schema
- [x] Add database insertion/deletion/modification functions
- [x] Implement index updates in digest endpoint
