### ISSUE TITLE
Domain blocklisting

### ISSUE THREAD

**Issue by codemicro** [codemicro/surchable#12]
**Description**: the intent of this search engine is to not allow commercial websites to be entered into the index. This can be done using the domain blocking lists used by adblockers like uBlock Origin.

If any webpage includes a reference to something within the block list, the entire domain should be excluded from the search engine index.

This issue is concerned with the server-side implementation *only* - see #18 for the client-side implementation.

**Branch:** [`12-domainBlocklisting`](https://github.com/codemicro/surchable/tree/12-domainBlocklisting)

**To-do:**
- [x] Update docs
- [x] Endpoint to block domains by crawler
- [x] Database function to deal with blocklist
  - [x] Update SQL schema
  - [x] Implement add function
  - [x] Implement query function 
  - [x] Implement remove function
 - [x] Add checks for blocked domains when queueing domains
