### ISSUE TITLE
Blocklist exclusions

### ISSUE THREAD

**Issue by codemicro** [codemicro/surchable#17]
**Description**: Sometimes, a domain may be incorrectly blocked by the crawler. To prevent this, a dedicated database table for blocklist exclusions will be created.

Eg: https://mincerafter42.github.io/ contains an "ad" but shouldn't be blocked.

**Related:** #12

**Branch:** n/a

**To-do:**
- [ ] Endpoint to override blocked domains
- [ ] Database function to deal with blocklist exclusions
  - [ ] Update SQL schema
  - [ ] Implement add function
  - [ ] Implement query function
