### ISSUE TITLE
Coordinator: add page load preflight endpoint

### ISSUE THREAD

**Issue by codemicro** [codemicro/surchable#2]
**Description**: The page load preflight endpoint should check to see if the page was requested recently (via the `page_loads` template) and return an appropriate response either telling the crawler to go ahead or to skip this page.

**Branch:** n/a

**To-do:**
- [x] Update docs
- [x] Add database query function
- [x] Reimplement URL normalisation using https://github.com/PuerkitoBio/purell
- [x] Add endpoint handler
