### ISSUE TITLE
Coordinator: add page load digest endpoint

### ISSUE THREAD

**Issue by codemicro** [codemicro/surchable#3]
**Description**: the page load digest endpoint is where crawlers can submit the results of a page load to the coordinator for storage in the database. This should update the `page_loads` table as well as a new `page_information` table.

The database should store:
* A unique ID for this page
* Foreign key to the entry in the `page_loads` table
* The page title
* The page meta description text
* The page's content text
* The raw page HTML
  * This could potentially be persisted to disk instead?

**Branch:** [`3-pageLoadDigestEndpoint`](https://github.com/codemicro/surchable/tree/3-pageLoadDigestEndpoint), #7

**To-do:**

- [x] #2
- [x] Update docs
- [x] Write new SQL table migration
- [x] Add database `page_loads` insert function
- [x] Add database `page_information` insert function
- [x] Add endpoint handler
