### ISSUE TITLE
Implemenent queue priorities

### ISSUE THREAD

**Issue by codemicro** [codemicro/surchable#9]
**Description**: Queue priorities will allow user-submitted domains and expired jobs to be submitted to the queue before anything else that was added to the queue, eg: by link discovery in crawled pages.

**Branch:** [`9-queuePriorities`](https://github.com/codemicro/surchable/tree/9-queuePriorities)

**To-do:**
- [x] Alter SQL schema
- [x] Alter job selection query
- [x] Implement queue prioritiy selection on new queue items
- [x] Set queue priority to 5 when a job is removed from the active job list
